name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: mothership

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy files
      run: |
        env