name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: mothership

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy files
      run: |
        mkdir /opt/mothership/myhome/releases/${{ github.run_number }}
        cp -r * /opt/mothership/myhome/releases/${{ github.run_number }}
        cd /opt/mothership/myhome/
        rm -rf current
        ln -s releases/${{ github.run_number }} current
        sudo docker compose restart
